# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=11)),
                ('created', models.DateTimeField()),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_eId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='id_management.Id'),
        ),
    ]
